trigger:
- main

variables:
- name: vmName
  value: nextCloudBicep
- name: resourceGroupName
  value: app-jlindsey2
- name: location
  value: Central US
- name: userName
  value: jimmy
- name: vnetName
  value: ansible-test-vnet

pool:
  vmImage: ubuntu-latest

jobs:
- job: Create_virtual_machine_and_configure_NextCloud
  timeoutInMinutes: 10
  steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'cccis-jlindsey-sandbox(ff95cccd-cbb7-41a2-b4ba-41917218c03c)'
        ScriptType: 'InlineScript'
        Inline: |
          $keyPath = $HOME + "/.ssh/"
          $privateKeyName = $(vmName) + "-key"
          $publicKeyName = $(vmName) + "-key.pub"
          $privateKeyPath = $keyPath + "/" + $privateKeyName
          $publicKeyPath  = $keyPath + "/" + $publicKeyName
          
          ssh-keygen -m PEM -t rsa -b 2048 -C $(vmName) -f $privateKeyPath -N ''
          
          $sshKey = Get-Content $publicKeyPath
          $secureSSHKey = ConvertTo-SecureString $sshKey -AsPlainText -Force

          New-AzResourceGroupDeployment -ResourceGroupName $(resourceGroupName) -TemplateFile $(System.DefaultWorkingDirectory)/bicep/virtualMachine.bicep -vmName $(vmName) `
          -location $(location) -vnetName $(vnetName) -adminUsername $(userName) -adminPasswordOrKey $secureSSHKey
    