trigger:
- main

variables:
- name: vmName
  value: nextCloudBicep
- name: resourceGroupName
  value: app-jlindsey2
- name: location
  value: Central US
- name: userName
  value: jimmy
- name: vnetName
  value: ansible-test-vnet

pool:
  vmImage: ubuntu-latest

jobs:
- job: Create_virtual_machine_and_configure_NextCloud
  timeoutInMinutes: 10
  steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'cccis-jlindsey-sandbox(ff95cccd-cbb7-41a2-b4ba-41917218c03c)'
      ScriptType: 'FilePath'
      ScriptPath: '$(System.DefaultWorkingDirectory)/genKeyAndCallBicep.ps1'
      ScriptArguments: '-VMName nextCloudBicep -ResourceGroupName app-jlindsey2 -Location "Central US" -UserName jimmy -VNetName ansible-test-vnet'
      azurePowerShellVersion: 'LatestVersion'
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'cccis-jlindsey-sandbox(ff95cccd-cbb7-41a2-b4ba-41917218c03c)'
      ScriptType: 'InlineScript'
      Inline: 'Get-Content "$(System.DefaultWorkingDirectory)/ansible/static.ini"'
      azurePowerShellVersion: 'LatestVersion' 
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10.12'
      addToPath: true
      architecture: 'x64'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'pip install ansible'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'ansible-playbook configureNextCloud.yml'
      workingDirectory: '$(System.DefaultWorkingDirectory)/ansible'